-- EVVEX Event and Ticket Creation Studio synchronization
-- Idempotent: safe to run after EVENT_PLATFORM_ROLE_MIGRATION.sql.
-- No tables are created or dropped by this checkpoint.

ALTER TABLE public.events
  ADD COLUMN IF NOT EXISTS admission_mode TEXT NOT NULL DEFAULT 'ticketed',
  ADD COLUMN IF NOT EXISTS contact_email TEXT,
  ADD COLUMN IF NOT EXISTS contact_phone TEXT,
  ADD COLUMN IF NOT EXISTS contact_instructions TEXT,
  ADD COLUMN IF NOT EXISTS presentation_cards JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS theme_id TEXT NOT NULL DEFAULT 'aurora',
  ADD COLUMN IF NOT EXISTS font_id TEXT NOT NULL DEFAULT 'font-sans';

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'events_admission_mode_check'
      AND conrelid = 'public.events'::regclass
  ) THEN
    ALTER TABLE public.events
      ADD CONSTRAINT events_admission_mode_check
      CHECK (admission_mode IN ('free', 'ticketed'));
  END IF;
END;
$$;

ALTER TABLE public.event_ticket_tiers
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS theme_id TEXT NOT NULL DEFAULT 'aurora',
  ADD COLUMN IF NOT EXISTS font_id TEXT NOT NULL DEFAULT 'font-sans';

UPDATE public.events
SET admission_mode = CASE
  WHEN EXISTS (
    SELECT 1
    FROM public.event_ticket_tiers tier
    WHERE tier.event_id = events.id
      AND tier.price_kobo > 0
  ) THEN 'ticketed'
  ELSE admission_mode
END
WHERE admission_mode IS NULL;

COMMENT ON COLUMN public.events.admission_mode IS 'Whether admission is free or ticketed; ticket tiers remain separate child records.';
COMMENT ON COLUMN public.events.presentation_cards IS 'Manually authored event highlights/program cards; never generated by the ebook AI flow.';
COMMENT ON COLUMN public.event_ticket_tiers.perks IS 'JSON array of manually authored ticket-tier perk/highlight cards.';
