import React, { useState, useEffect, useMemo } from 'react';
import { supabase } from '../supabase';
import { 
  Users, 
  Wallet, 
  Search, 
  Filter, 
  RefreshCw, 
  Eye, 
  CheckCircle2, 
  Ban, 
  Clock, 
  DollarSign, 
  BookOpen, 
  TrendingUp, 
  Copy, 
  Check, 
  X, 
  AlertCircle,
  Building2,
  CreditCard,
  Send,
  ExternalLink,
  ShieldCheck,
  ChevronRight,
  ArrowUpRight
} from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';

interface MPRItem {
  id: string;
  name: string;
  email: string;
  mpr_code: string;
  status: 'active' | 'pending' | 'suspended';
  commission_rate: number;
  total_earnings: number;
  pending_earnings: number;
  paid_earnings: number;
  bank_name: string;
  account_number: string;
  account_name: string;
  created_at: string;
  recruits: any[];
  books: any[];
  total_revenue: number;
}

export const AdminMprMonitoring: React.FC = () => {
  const [loading, setLoading] = useState(true);
  const [mprList, setMprList] = useState<MPRItem[]>([]);
  const [searchQuery, setSearchQuery] = useState('');
  const [statusFilter, setStatusFilter] = useState<'all' | 'active' | 'pending' | 'suspended'>('all');
  const [payoutFilter, setPayoutFilter] = useState<'all' | 'pending_payout' | 'settled'>('all');
  const [copiedCode, setCopiedCode] = useState<string | null>(null);

  // Detail Modal State
  const [selectedMpr, setSelectedMpr] = useState<MPRItem | null>(null);
  const [detailTab, setDetailTab] = useState<'recruits' | 'books' | 'payout'>('recruits');
  
  // Payout Modal State
  const [payoutModalMpr, setPayoutModalMpr] = useState<MPRItem | null>(null);
  const [payoutAmount, setPayoutAmount] = useState('');
  const [payoutNotes, setPayoutNotes] = useState('');
  const [processingPayout, setProcessingPayout] = useState(false);
  const [actionFeedback, setActionFeedback] = useState<{ type: 'success' | 'error'; text: string } | null>(null);

  const fetchMprMonitoringData = async () => {
    setLoading(true);
    setActionFeedback(null);
    try {
      // 1. Fetch MPR users
      const { data: rawUsers, error: usersErr } = await supabase
        .from('users')
        .select('id, email, full_name, username, account_tier, role, mpr_code, mpr_commission_rate, total_mpr_earnings, pending_mpr_earnings, bank_name, account_number, account_name, created_at, is_suspended, status')
        .or('account_tier.eq.marketing_partner,account_tier.eq.mpr,role.eq.marketing_partner,mpr_code.not.is.null')
        .order('created_at', { ascending: false });

      if (usersErr) throw usersErr;

      const mprs = rawUsers || [];
      const mprCodes = mprs.map(u => u.mpr_code).filter(Boolean);
      const mprIds = mprs.map(u => u.id);

      // 2. Fetch all recruits (authors/users referred by these MPRs)
      let allRecruits: any[] = [];
      if (mprCodes.length > 0 || mprIds.length > 0) {
        const { data: recruitsData } = await supabase
          .from('users')
          .select('id, email, full_name, username, referred_by, account_tier, role, created_at')
          .or(`referred_by.in.(${mprCodes.join(',')}),referred_by.in.(${mprIds.join(',')})`);
        allRecruits = recruitsData || [];
      }

      const recruitIds = allRecruits.map(r => r.id);

      // 3. Fetch all books published by these recruits
      let allBooks: any[] = [];
      if (recruitIds.length > 0) {
        const { data: booksData } = await supabase
          .from('books')
          .select('id, title, user_id, author_name, price, sales_count, status, created_at')
          .in('user_id', recruitIds);
        allBooks = booksData || [];
      }

      // 4. Assemble the enriched list
      const enriched: MPRItem[] = mprs.map(u => {
        const userRecruits = allRecruits.filter(r => 
          (u.mpr_code && r.referred_by === u.mpr_code) || r.referred_by === u.id
        );
        const userRecruitIds = userRecruits.map(r => r.id);
        const userBooks = allBooks.filter(b => userRecruitIds.includes(b.user_id));

        // Calculate revenue generated by recruits
        const revenue = userBooks.reduce((sum, b) => sum + ((b.price || 0) * (b.sales_count || 0)), 0);
        const totalEarnings = Number(u.total_mpr_earnings || 0);
        const pendingEarnings = Number(u.pending_mpr_earnings || 0);
        const paidEarnings = Math.max(0, totalEarnings - pendingEarnings);

        let derivedStatus: 'active' | 'pending' | 'suspended' = 'active';
        if (u.is_suspended || u.status === 'suspended') {
          derivedStatus = 'suspended';
        } else if (u.status === 'pending' || (!u.mpr_code && u.status !== 'active')) {
          derivedStatus = 'pending';
        }

        return {
          id: u.id,
          name: u.full_name || u.username || u.email?.split('@')[0] || 'Marketing Partner',
          email: u.email || 'N/A',
          mpr_code: u.mpr_code || `MPR-${u.id.substring(0, 6).toUpperCase()}`,
          status: derivedStatus,
          commission_rate: u.mpr_commission_rate || 10,
          total_earnings: totalEarnings,
          pending_earnings: pendingEarnings,
          paid_earnings: paidEarnings,
          bank_name: u.bank_name || '',
          account_number: u.account_number || '',
          account_name: u.account_name || '',
          created_at: u.created_at,
          recruits: userRecruits,
          books: userBooks,
          total_revenue: revenue
        };
      });

      setMprList(enriched);
    } catch (err: any) {
      console.error('[Admin MPR Monitoring] Failed to load data:', err);
      setActionFeedback({ type: 'error', text: err.message || 'Failed to load MPR data.' });
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchMprMonitoringData();
  }, []);

  const handleCopyCode = (code: string) => {
    navigator.clipboard.writeText(code);
    setCopiedCode(code);
    setTimeout(() => setCopiedCode(null), 2500);
  };

  // Actions
  const handleApprove = async (mpr: MPRItem) => {
    setActionFeedback(null);
    try {
      const code = mpr.mpr_code || `MPR-${mpr.id.substring(0, 6).toUpperCase()}`;
      const { error } = await supabase
        .from('users')
        .update({
          status: 'active',
          is_suspended: false,
          account_tier: 'marketing_partner',
          mpr_code: code
        })
        .eq('id', mpr.id);

      if (error) throw error;

      setActionFeedback({ type: 'success', text: `MPR partner ${mpr.name} approved successfully!` });
      fetchMprMonitoringData();
    } catch (err: any) {
      setActionFeedback({ type: 'error', text: err.message || 'Approval failed.' });
    }
  };

  const handleToggleSuspend = async (mpr: MPRItem) => {
    setActionFeedback(null);
    const newStatus = mpr.status === 'suspended' ? 'active' : 'suspended';
    const isSuspended = newStatus === 'suspended';
    try {
      const { error } = await supabase
        .from('users')
        .update({
          status: newStatus,
          is_suspended: isSuspended
        })
        .eq('id', mpr.id);

      if (error) throw error;

      setActionFeedback({ 
        type: 'success', 
        text: `MPR partner ${mpr.name} has been ${isSuspended ? 'suspended' : 'reactivated'}.` 
      });
      fetchMprMonitoringData();
    } catch (err: any) {
      setActionFeedback({ type: 'error', text: err.message || 'Status update failed.' });
    }
  };

  const handleExecutePayout = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!payoutModalMpr) return;

    const amount = parseFloat(payoutAmount);
    if (!amount || amount <= 0) {
      alert('Please enter a valid payout amount.');
      return;
    }

    setProcessingPayout(true);
    setActionFeedback(null);
    try {
      const currentPending = payoutModalMpr.pending_earnings || 0;
      const currentTotal = payoutModalMpr.total_earnings || 0;
      const newPending = Math.max(0, currentPending - amount);

      // 1. Update user's pending MPR earnings in users table
      const { error: updateErr } = await supabase
        .from('users')
        .update({
          pending_mpr_earnings: newPending
        })
        .eq('id', payoutModalMpr.id);

      if (updateErr) throw updateErr;

      // 2. Insert transaction record if transactions table exists
      try {
        await supabase.from('transactions').insert({
          user_id: payoutModalMpr.id,
          amount: amount,
          type: 'payout',
          category: 'mpr_commission',
          status: 'completed',
          description: `MPR Commission Payout: ₦${amount.toLocaleString()} to ${payoutModalMpr.bank_name || 'Bank'} (${payoutNotes || 'Manual Payout'})`,
          created_at: new Date().toISOString()
        });
      } catch (tErr) {
        console.warn('Optional transaction log bypassed:', tErr);
      }

      setActionFeedback({
        type: 'success',
        text: `Successfully processed payout of ₦${amount.toLocaleString()} for ${payoutModalMpr.name}!`
      });

      setPayoutModalMpr(null);
      setPayoutAmount('');
      setPayoutNotes('');
      fetchMprMonitoringData();
    } catch (err: any) {
      console.error('[Payout Error]:', err);
      setActionFeedback({ type: 'error', text: err.message || 'Payout processing failed.' });
    } finally {
      setProcessingPayout(false);
    }
  };

  // Filtered list
  const filteredList = useMemo(() => {
    return mprList.filter(m => {
      const matchesSearch = 
        m.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
        m.email.toLowerCase().includes(searchQuery.toLowerCase()) ||
        m.mpr_code.toLowerCase().includes(searchQuery.toLowerCase());

      const matchesStatus = statusFilter === 'all' || m.status === statusFilter;

      const matchesPayout = 
        payoutFilter === 'all' ||
        (payoutFilter === 'pending_payout' && m.pending_earnings > 0) ||
        (payoutFilter === 'settled' && m.pending_earnings === 0);

      return matchesSearch && matchesStatus && matchesPayout;
    });
  }, [mprList, searchQuery, statusFilter, payoutFilter]);

  // Totals
  const totalStats = useMemo(() => {
    return {
      totalMprs: mprList.length,
      activeMprs: mprList.filter(m => m.status === 'active').length,
      pendingMprs: mprList.filter(m => m.status === 'pending').length,
      suspendedMprs: mprList.filter(m => m.status === 'suspended').length,
      totalRecruits: mprList.reduce((sum, m) => sum + m.recruits.length, 0),
      totalBooks: mprList.reduce((sum, m) => sum + m.books.length, 0),
      totalRevenue: mprList.reduce((sum, m) => sum + m.total_revenue, 0),
      totalEarned: mprList.reduce((sum, m) => sum + m.total_earnings, 0),
      totalPaid: mprList.reduce((sum, m) => sum + m.paid_earnings, 0),
      totalPending: mprList.reduce((sum, m) => sum + m.pending_earnings, 0),
    };
  }, [mprList]);

  return (
    <div className="space-y-6">
      {/* Top Header Bar */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-100 pb-4">
        <div>
          <div className="flex items-center gap-2">
            <h2 className="text-2xl font-black text-slate-900 tracking-tight flex items-center gap-2">
              <Users className="w-6 h-6 text-purple-600" /> MPR Monitoring Dashboard
            </h2>
            <Badge className="bg-purple-100 text-purple-800 border-none font-bold text-xs uppercase px-2.5">
              Live Monitoring
            </Badge>
          </div>
          <p className="text-sm text-slate-500 mt-1">
            Real-time tracking of marketing partner recruitments, published books, revenue generation, and commission payouts.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <Button
            variant="outline"
            size="sm"
            onClick={fetchMprMonitoringData}
            disabled={loading}
            className="rounded-xl h-10 px-4 text-xs font-bold gap-1.5 border-slate-200 hover:bg-slate-50 cursor-pointer"
          >
            <RefreshCw className={`w-3.5 h-3.5 ${loading ? 'animate-spin' : ''}`} />
            <span>Refresh</span>
          </Button>
        </div>
      </div>

      {/* Feedback Toast */}
      {actionFeedback && (
        <div className={`p-4 rounded-2xl flex items-center justify-between gap-3 text-xs font-bold shadow-xs animate-in fade-in duration-200 ${
          actionFeedback.type === 'success'
            ? 'bg-emerald-50 text-emerald-800 border border-emerald-200'
            : 'bg-red-50 text-red-800 border border-red-200'
        }`}>
          <div className="flex items-center gap-2">
            {actionFeedback.type === 'success' ? <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" /> : <AlertCircle className="w-4 h-4 text-red-600 shrink-0" />}
            <span>{actionFeedback.text}</span>
          </div>
          <button onClick={() => setActionFeedback(null)} className="text-slate-400 hover:text-slate-600 p-1">
            ✕
          </button>
        </div>
      )}

      {/* Summary KPI Cards */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        {/* Total Partners */}
        <Card className="rounded-2xl border-slate-100 p-5 bg-gradient-to-br from-purple-900 to-indigo-950 text-white shadow-md">
          <div className="flex items-center justify-between">
            <span className="text-xs uppercase font-bold text-purple-200">Total Partners</span>
            <Users className="w-4 h-4 text-purple-300" />
          </div>
          <h3 className="text-2xl sm:text-3xl font-black mt-2">
            {totalStats.totalMprs}
          </h3>
          <div className="flex items-center gap-2 mt-2 text-[11px] font-semibold text-purple-200">
            <span className="text-emerald-300 font-bold">{totalStats.activeMprs} Active</span>
            <span>•</span>
            <span className="text-amber-300">{totalStats.pendingMprs} Pending</span>
            <span>•</span>
            <span className="text-red-300">{totalStats.suspendedMprs} Suspended</span>
          </div>
        </Card>

        {/* Recruits & Published Books */}
        <Card className="rounded-2xl border-slate-100 p-5 bg-white shadow-xs">
          <div className="flex items-center justify-between">
            <span className="text-xs uppercase font-bold text-slate-400">Network Recruits</span>
            <TrendingUp className="w-4 h-4 text-purple-600" />
          </div>
          <h3 className="text-2xl sm:text-3xl font-black text-slate-900 mt-2">
            {totalStats.totalRecruits}
          </h3>
          <p className="text-[11px] text-slate-500 mt-2 font-medium flex items-center gap-1.5">
            <BookOpen className="w-3.5 h-3.5 text-purple-600" />
            <span className="font-bold text-slate-700">{totalStats.totalBooks}</span> Books Published
          </p>
        </Card>

        {/* Total Revenue Generated */}
        <Card className="rounded-2xl border-slate-100 p-5 bg-white shadow-xs">
          <div className="flex items-center justify-between">
            <span className="text-xs uppercase font-bold text-slate-400">Recruit Revenue</span>
            <DollarSign className="w-4 h-4 text-emerald-600" />
          </div>
          <h3 className="text-2xl sm:text-3xl font-black text-slate-900 mt-2">
            ₦{totalStats.totalRevenue.toLocaleString()}
          </h3>
          <p className="text-[11px] text-slate-500 mt-2 font-medium">
            Generated from recruit eBook sales
          </p>
        </Card>

        {/* Commission Payouts */}
        <Card className="rounded-2xl border-slate-100 p-5 bg-white shadow-xs">
          <div className="flex items-center justify-between">
            <span className="text-xs uppercase font-bold text-slate-400">Commissions</span>
            <Wallet className="w-4 h-4 text-amber-600" />
          </div>
          <h3 className="text-2xl sm:text-3xl font-black text-slate-900 mt-2">
            ₦{totalStats.totalEarned.toLocaleString()}
          </h3>
          <div className="flex items-center gap-2 mt-2 text-[11px] font-semibold">
            <span className="text-emerald-600 font-bold">₦{totalStats.totalPaid.toLocaleString()} Paid</span>
            <span>•</span>
            <span className="text-amber-600 font-bold">₦{totalStats.totalPending.toLocaleString()} Pending</span>
          </div>
        </Card>
      </div>

      {/* Filter & Search Toolbar */}
      <div className="flex flex-col md:flex-row items-center justify-between gap-3 bg-white p-3.5 rounded-2xl border border-slate-100 shadow-xs">
        <div className="relative w-full md:w-80">
          <Search className="w-4 h-4 absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400" />
          <Input
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search partner name, email, or code..."
            className="pl-9 rounded-xl h-10 text-xs font-medium border-slate-200"
          />
        </div>

        <div className="flex items-center gap-2 w-full md:w-auto flex-wrap">
          {/* Status Filter */}
          <div className="flex items-center gap-1.5 bg-slate-100 p-1 rounded-xl text-xs font-bold">
            {(['all', 'active', 'pending', 'suspended'] as const).map((st) => (
              <button
                key={st}
                onClick={() => setStatusFilter(st)}
                className={`px-3 py-1.5 rounded-lg capitalize transition-all cursor-pointer ${
                  statusFilter === st
                    ? 'bg-white text-slate-900 shadow-xs'
                    : 'text-slate-500 hover:text-slate-900'
                }`}
              >
                {st}
              </button>
            ))}
          </div>

          {/* Payout Filter */}
          <select
            value={payoutFilter}
            onChange={(e: any) => setPayoutFilter(e.target.value)}
            className="bg-slate-100 border-none rounded-xl px-3 py-2 text-xs font-bold text-slate-700 cursor-pointer h-9"
          >
            <option value="all">All Payouts</option>
            <option value="pending_payout">Pending Payout Only</option>
            <option value="settled">Fully Settled</option>
          </select>
        </div>
      </div>

      {/* MPR Accounts Table */}
      <Card className="rounded-2xl border-slate-100 shadow-xs overflow-hidden bg-white">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead className="bg-slate-50 text-slate-500 uppercase font-bold border-b border-slate-100 text-[11px] tracking-wider">
              <tr>
                <th className="px-5 py-4">MPR Partner</th>
                <th className="px-4 py-4">Status</th>
                <th className="px-4 py-4 text-center">Recruits</th>
                <th className="px-4 py-4 text-center">Books</th>
                <th className="px-4 py-4">Revenue Gen.</th>
                <th className="px-4 py-4">Commission</th>
                <th className="px-4 py-4">Bank Details</th>
                <th className="px-5 py-4 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {loading ? (
                <tr>
                  <td colSpan={8} className="px-6 py-12 text-center text-slate-400 font-semibold animate-pulse">
                    Loading marketing partner directory and analytics...
                  </td>
                </tr>
              ) : filteredList.length === 0 ? (
                <tr>
                  <td colSpan={8} className="px-6 py-12 text-center text-slate-400 italic">
                    No marketing partners match your search and filter criteria.
                  </td>
                </tr>
              ) : (
                filteredList.map((m) => (
                  <tr key={m.id} className="hover:bg-purple-50/20 transition-colors">
                    {/* Partner Name & Code */}
                    <td className="px-5 py-4">
                      <div>
                        <div className="font-bold text-slate-900 text-sm flex items-center gap-1.5">
                          <span>{m.name}</span>
                        </div>
                        <div className="text-slate-400 text-[11px] truncate max-w-xs">{m.email}</div>
                        <div className="flex items-center gap-1 mt-1">
                          <span className="font-mono text-[10px] font-bold text-purple-600 bg-purple-50 px-1.5 py-0.5 rounded">
                            {m.mpr_code}
                          </span>
                          <button
                            onClick={() => handleCopyCode(m.mpr_code)}
                            className="text-slate-400 hover:text-purple-600 p-0.5 cursor-pointer"
                            title="Copy Code"
                          >
                            {copiedCode === m.mpr_code ? <Check className="w-3 h-3 text-emerald-600" /> : <Copy className="w-3 h-3" />}
                          </button>
                        </div>
                      </div>
                    </td>

                    {/* Status */}
                    <td className="px-4 py-4">
                      <Badge className={
                        m.status === 'active'
                          ? 'bg-emerald-100 text-emerald-800 border-none font-bold text-[10px]'
                          : m.status === 'pending'
                          ? 'bg-amber-100 text-amber-800 border-none font-bold text-[10px]'
                          : 'bg-red-100 text-red-800 border-none font-bold text-[10px]'
                      }>
                        <span className={`w-1.5 h-1.5 rounded-full mr-1 ${
                          m.status === 'active' ? 'bg-emerald-500' : m.status === 'pending' ? 'bg-amber-500' : 'bg-red-500'
                        }`} />
                        <span className="capitalize">{m.status}</span>
                      </Badge>
                    </td>

                    {/* Recruits */}
                    <td className="px-4 py-4 text-center font-bold text-slate-800">
                      <span className="inline-flex items-center justify-center bg-slate-100 text-slate-700 px-2.5 py-1 rounded-lg text-xs">
                        {m.recruits.length}
                      </span>
                    </td>

                    {/* Books Published */}
                    <td className="px-4 py-4 text-center font-bold text-slate-800">
                      <span className="inline-flex items-center justify-center bg-purple-50 text-purple-700 px-2.5 py-1 rounded-lg text-xs">
                        {m.books.length}
                      </span>
                    </td>

                    {/* Revenue Generated */}
                    <td className="px-4 py-4 font-bold text-slate-900">
                      ₦{m.total_revenue.toLocaleString()}
                    </td>

                    {/* Commission */}
                    <td className="px-4 py-4">
                      <div className="font-bold text-slate-900">
                        ₦{m.total_earnings.toLocaleString()}
                      </div>
                      <div className="text-[10px] mt-0.5 flex items-center gap-1.5">
                        <span className="text-emerald-600 font-semibold">₦{m.paid_earnings.toLocaleString()} paid</span>
                        {m.pending_earnings > 0 && (
                          <span className="text-amber-600 font-bold bg-amber-50 px-1.5 py-0.2 rounded">
                            ₦{m.pending_earnings.toLocaleString()} due
                          </span>
                        )}
                      </div>
                    </td>

                    {/* Bank Details */}
                    <td className="px-4 py-4 text-slate-600">
                      {m.bank_name ? (
                        <div>
                          <div className="font-bold text-slate-800 text-[11px]">{m.bank_name}</div>
                          <div className="font-mono text-[10px] text-slate-500">{m.account_number}</div>
                          {m.account_name && <div className="text-[10px] text-slate-400 truncate max-w-[120px]">{m.account_name}</div>}
                        </div>
                      ) : (
                        <span className="text-slate-400 italic text-[11px]">Not provided</span>
                      )}
                    </td>

                    {/* Actions */}
                    <td className="px-5 py-4 text-right">
                      <div className="flex items-center justify-end gap-1.5">
                        {/* View Details */}
                        <Button
                          size="sm"
                          variant="outline"
                          onClick={() => {
                            setSelectedMpr(m);
                            setDetailTab('recruits');
                          }}
                          className="h-8 px-2.5 text-xs font-bold rounded-lg border-slate-200 text-slate-700 hover:bg-slate-100 cursor-pointer gap-1"
                          title="View Details"
                        >
                          <Eye className="w-3.5 h-3.5" />
                          <span>Details</span>
                        </Button>

                        {/* Approve (if pending) */}
                        {m.status === 'pending' && (
                          <Button
                            size="sm"
                            onClick={() => handleApprove(m)}
                            className="h-8 px-2.5 text-xs font-bold rounded-lg bg-emerald-600 hover:bg-emerald-700 text-white cursor-pointer gap-1"
                            title="Approve Partner"
                          >
                            <CheckCircle2 className="w-3.5 h-3.5" />
                            <span>Approve</span>
                          </Button>
                        )}

                        {/* Suspend / Reactivate */}
                        {m.status === 'active' ? (
                          <Button
                            size="sm"
                            variant="outline"
                            onClick={() => handleToggleSuspend(m)}
                            className="h-8 px-2 text-xs font-bold rounded-lg border-red-200 text-red-600 hover:bg-red-50 cursor-pointer"
                            title="Suspend Partner"
                          >
                            <Ban className="w-3.5 h-3.5" />
                          </Button>
                        ) : m.status === 'suspended' ? (
                          <Button
                            size="sm"
                            variant="outline"
                            onClick={() => handleToggleSuspend(m)}
                            className="h-8 px-2.5 text-xs font-bold rounded-lg border-emerald-200 text-emerald-600 hover:bg-emerald-50 cursor-pointer gap-1"
                            title="Reactivate Partner"
                          >
                            <CheckCircle2 className="w-3.5 h-3.5" />
                            <span>Reactivate</span>
                          </Button>
                        ) : null}

                        {/* Payout Commission Button */}
                        {m.pending_earnings > 0 && (
                          <Button
                            size="sm"
                            onClick={() => {
                              setPayoutModalMpr(m);
                              setPayoutAmount(String(m.pending_earnings));
                              setPayoutNotes('');
                            }}
                            className="h-8 px-2.5 text-xs font-bold rounded-lg bg-purple-600 hover:bg-purple-700 text-white cursor-pointer gap-1 shadow-xs"
                            title="Payout Commission"
                          >
                            <Wallet className="w-3.5 h-3.5" />
                            <span>Payout</span>
                          </Button>
                        )}
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </Card>

      {/* DETAIL MODAL FOR MPR */}
      {selectedMpr && (
        <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-xs flex items-center justify-center p-3 sm:p-4 overflow-y-auto">
          <Card className="w-full max-w-3xl max-h-[90vh] flex flex-col bg-white rounded-2xl shadow-2xl border border-slate-200 overflow-hidden animate-in fade-in duration-150">
            {/* Modal Header */}
            <div className="p-5 border-b border-slate-100 flex items-center justify-between bg-slate-50/50 shrink-0">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-purple-100 text-purple-700 flex items-center justify-center font-bold text-lg">
                  {selectedMpr.name.substring(0, 2).toUpperCase()}
                </div>
                <div>
                  <h3 className="font-bold text-base text-slate-900 leading-tight flex items-center gap-2">
                    <span>{selectedMpr.name}</span>
                    <Badge className={
                      selectedMpr.status === 'active'
                        ? 'bg-emerald-100 text-emerald-800'
                        : selectedMpr.status === 'pending'
                        ? 'bg-amber-100 text-amber-800'
                        : 'bg-red-100 text-red-800'
                    }>
                      {selectedMpr.status}
                    </Badge>
                  </h3>
                  <p className="text-xs text-slate-500 font-mono mt-0.5">
                    {selectedMpr.email} • Code: {selectedMpr.mpr_code}
                  </p>
                </div>
              </div>
              <button
                onClick={() => setSelectedMpr(null)}
                className="w-8 h-8 rounded-lg text-slate-400 hover:text-slate-600 hover:bg-slate-100 flex items-center justify-center transition-colors cursor-pointer"
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            {/* Quick Metrics Strip */}
            <div className="grid grid-cols-3 gap-2 p-4 bg-purple-50/40 border-b border-purple-100 text-center shrink-0">
              <div>
                <p className="text-[10px] uppercase font-bold text-slate-400">Total Recruits</p>
                <p className="text-lg font-black text-slate-900">{selectedMpr.recruits.length}</p>
              </div>
              <div>
                <p className="text-[10px] uppercase font-bold text-slate-400">Books Published</p>
                <p className="text-lg font-black text-purple-700">{selectedMpr.books.length}</p>
              </div>
              <div>
                <p className="text-[10px] uppercase font-bold text-slate-400">Due Payout</p>
                <p className="text-lg font-black text-amber-700">₦{selectedMpr.pending_earnings.toLocaleString()}</p>
              </div>
            </div>

            {/* Tabs */}
            <div className="flex border-b border-slate-100 px-5 pt-2 gap-4 text-xs font-bold shrink-0">
              <button
                onClick={() => setDetailTab('recruits')}
                className={`pb-3 border-b-2 transition-colors cursor-pointer ${
                  detailTab === 'recruits'
                    ? 'border-purple-600 text-purple-600'
                    : 'border-transparent text-slate-400 hover:text-slate-600'
                }`}
              >
                Authors & Recruits ({selectedMpr.recruits.length})
              </button>
              <button
                onClick={() => setDetailTab('books')}
                className={`pb-3 border-b-2 transition-colors cursor-pointer ${
                  detailTab === 'books'
                    ? 'border-purple-600 text-purple-600'
                    : 'border-transparent text-slate-400 hover:text-slate-600'
                }`}
              >
                Published Books ({selectedMpr.books.length})
              </button>
              <button
                onClick={() => setDetailTab('payout')}
                className={`pb-3 border-b-2 transition-colors cursor-pointer ${
                  detailTab === 'payout'
                    ? 'border-purple-600 text-purple-600'
                    : 'border-transparent text-slate-400 hover:text-slate-600'
                }`}
              >
                Bank & Commission Payout
              </button>
            </div>

            {/* Tab Body */}
            <div className="p-5 flex-1 overflow-y-auto space-y-4">
              {detailTab === 'recruits' && (
                <div>
                  {selectedMpr.recruits.length === 0 ? (
                    <div className="py-12 text-center text-slate-400 text-xs italic">
                      No authors registered under this MPR code yet.
                    </div>
                  ) : (
                    <div className="space-y-2">
                      {selectedMpr.recruits.map((r, i) => (
                        <div key={r.id || i} className="p-3.5 rounded-xl border border-slate-100 bg-slate-50/50 flex items-center justify-between">
                          <div>
                            <h4 className="font-bold text-xs text-slate-900">{r.full_name || r.username || 'Author'}</h4>
                            <p className="text-[11px] text-slate-500">{r.email}</p>
                            <span className="text-[10px] text-slate-400">Joined: {new Date(r.created_at).toLocaleDateString()}</span>
                          </div>
                          <Badge className="bg-purple-100 text-purple-700 border-none font-bold text-[10px]">
                            {r.account_tier || 'Author'}
                          </Badge>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              )}

              {detailTab === 'books' && (
                <div>
                  {selectedMpr.books.length === 0 ? (
                    <div className="py-12 text-center text-slate-400 text-xs italic">
                      No books published by recruits under this MPR yet.
                    </div>
                  ) : (
                    <div className="space-y-2">
                      {selectedMpr.books.map((b, i) => (
                        <div key={b.id || i} className="p-3.5 rounded-xl border border-slate-100 bg-slate-50/50 flex items-center justify-between">
                          <div>
                            <h4 className="font-bold text-xs text-slate-900">{b.title}</h4>
                            <p className="text-[11px] text-slate-500">By {b.author_name || 'Recruit Author'}</p>
                            <span className="text-[10px] text-slate-400 font-semibold">
                              ₦{(b.price || 0).toLocaleString()} • {b.sales_count || 0} sales
                            </span>
                          </div>
                          <Badge className="bg-emerald-100 text-emerald-800 border-none font-bold text-[10px]">
                            ₦{((b.price || 0) * (b.sales_count || 0)).toLocaleString()} revenue
                          </Badge>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              )}

              {detailTab === 'payout' && (
                <div className="space-y-4">
                  <div className="p-4 rounded-xl border border-slate-200 bg-slate-50 space-y-2">
                    <h4 className="font-bold text-xs uppercase tracking-wider text-slate-600">Bank Account Details</h4>
                    <div className="grid grid-cols-2 gap-2 text-xs">
                      <div>
                        <span className="text-slate-400 block text-[10px] uppercase font-bold">Bank Name</span>
                        <span className="font-bold text-slate-800">{selectedMpr.bank_name || 'Not provided'}</span>
                      </div>
                      <div>
                        <span className="text-slate-400 block text-[10px] uppercase font-bold">Account Number</span>
                        <span className="font-mono font-bold text-slate-800">{selectedMpr.account_number || 'Not provided'}</span>
                      </div>
                      <div className="col-span-2">
                        <span className="text-slate-400 block text-[10px] uppercase font-bold">Account Name</span>
                        <span className="font-bold text-slate-800">{selectedMpr.account_name || 'Not provided'}</span>
                      </div>
                    </div>
                  </div>

                  <div className="p-4 rounded-xl border border-amber-200 bg-amber-50/50 space-y-3">
                    <div className="flex items-center justify-between">
                      <div>
                        <h4 className="font-bold text-xs text-amber-900">Pending Commission Due</h4>
                        <p className="text-[11px] text-amber-700">Earnings awaiting settlement</p>
                      </div>
                      <span className="text-xl font-black text-amber-900">
                        ₦{selectedMpr.pending_earnings.toLocaleString()}
                      </span>
                    </div>

                    {selectedMpr.pending_earnings > 0 ? (
                      <Button
                        onClick={() => {
                          setPayoutModalMpr(selectedMpr);
                          setPayoutAmount(String(selectedMpr.pending_earnings));
                          setPayoutNotes('');
                        }}
                        className="w-full bg-amber-600 hover:bg-amber-700 text-white font-bold text-xs rounded-xl h-9 cursor-pointer gap-1.5"
                      >
                        <Wallet className="w-3.5 h-3.5" />
                        <span>Settle Payout Now</span>
                      </Button>
                    ) : (
                      <p className="text-[11px] text-emerald-700 font-bold flex items-center gap-1">
                        <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600" />
                        All commissions currently settled and paid out.
                      </p>
                    )}
                  </div>
                </div>
              )}
            </div>
          </Card>
        </div>
      )}

      {/* PAYOUT MODAL */}
      {payoutModalMpr && (
        <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-xs flex items-center justify-center p-3 sm:p-4 overflow-y-auto">
          <Card className="w-full max-w-md bg-white rounded-2xl shadow-2xl border border-slate-200 overflow-hidden animate-in fade-in duration-150">
            <div className="p-4 border-b border-slate-100 flex items-center justify-between bg-purple-50/50">
              <div className="flex items-center gap-2">
                <Wallet className="w-5 h-5 text-purple-600" />
                <h3 className="font-bold text-sm text-slate-900">Process Commission Payout</h3>
              </div>
              <button
                onClick={() => setPayoutModalMpr(null)}
                className="text-slate-400 hover:text-slate-600 p-1"
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            <form onSubmit={handleExecutePayout} className="p-5 space-y-4">
              <div className="p-3 bg-purple-50 rounded-xl space-y-1">
                <div className="text-xs font-bold text-purple-900">{payoutModalMpr.name}</div>
                <div className="text-[11px] text-purple-700">
                  {payoutModalMpr.bank_name ? `${payoutModalMpr.bank_name} • ${payoutModalMpr.account_number}` : 'No bank details configured'}
                </div>
                <div className="text-xs font-black text-purple-900 pt-1">
                  Due Amount: ₦{payoutModalMpr.pending_earnings.toLocaleString()}
                </div>
              </div>

              <div className="space-y-1.5">
                <label className="text-xs font-bold text-slate-700 uppercase">Payout Amount (₦) *</label>
                <Input
                  type="number"
                  min="1"
                  max={payoutModalMpr.pending_earnings}
                  value={payoutAmount}
                  onChange={(e) => setPayoutAmount(e.target.value)}
                  placeholder="Enter amount to pay"
                  className="rounded-xl h-10 text-xs font-medium"
                  required
                />
              </div>

              <div className="space-y-1.5">
                <label className="text-xs font-bold text-slate-700 uppercase">Reference / Notes</label>
                <Input
                  value={payoutNotes}
                  onChange={(e) => setPayoutNotes(e.target.value)}
                  placeholder="e.g. Bank Transfer Ref / Batch #104"
                  className="rounded-xl h-10 text-xs font-medium"
                />
              </div>

              <div className="flex gap-2 pt-2">
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => setPayoutModalMpr(null)}
                  className="w-1/2 rounded-xl h-10 text-xs cursor-pointer"
                >
                  Cancel
                </Button>
                <Button
                  type="submit"
                  disabled={processingPayout}
                  className="w-1/2 bg-purple-600 hover:bg-purple-700 text-white font-bold rounded-xl h-10 text-xs cursor-pointer"
                >
                  {processingPayout ? 'Recording...' : 'Confirm Payout'}
                </Button>
              </div>
            </form>
          </Card>
        </div>
      )}
    </div>
  );
};
